import {
  FaReact,
  FaNodeJs,
  FaPython,
  FaDocker,
  FaGithub,
  FaLinkedin,
  FaMediumM,
  FaInstagram,
} from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import {
  SiNextdotjs,
  SiTypescript,
  SiTailwindcss,
  SiExpress,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiLinux,
  SiNginx,
  SiSelenium,
  SiGithubactions,
  SiGitlab,
  SiVite,
  SiPostman,
  SiRabbitmq,
  SiLangchain,
} from "react-icons/si";
import { TbBrandTypescript, TbBrandRedux } from "react-icons/tb";
import { BsGit } from "react-icons/bs";

export const iconMap = {
  TbBrandTypescript,
  SiTypescript,
  SiNextdotjs,
  FaReact,
  FaNodeJs,
  FaPython,
  SiTailwindcss,
  TbBrandRedux,
  SiExpress,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  FaDocker,
  BsGit,
  SiLinux,
  SiNginx,
  SiSelenium,
  SiGithubactions,
  SiGitlab,
  SiVite,
  SiPostman,
  SiRabbitmq,
  SiLangchain,
  FaGithub,
  FaLinkedin,
  FaMediumM,
  FaInstagram,
  FaXTwitter,
};
