"use client";
import ReactGA from 'react-ga';
import { useEffect } from "react"
import { Providers } from "./providers";
import Header from "../components/Header";
import { usePathname } from "next/navigation";
import "../styles/main.scss";
// import { Metadata } from "next";
// import Favicon from "/public/images/favicon.png";

//TODO: Its use client so we can't use metadata in this part have to fix it
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by create next app",
//   icons: {
//     icon: Favicon.src,
//     apple: "",
//   },
// };

export default function RootLayout({ children }) {

  const pathname = usePathname();
  
  const initGA = () => {
    ReactGA.initialize("G-GD32MHWBE6");
  };
  
  const logPageView = () => {
    ReactGA.set({ page: window.location.pathname });
    ReactGA.pageview(window.location.pathname);
  };

  useEffect(() => {
    if (!window.GA_INITIALIZED) {
      initGA();
      window.GA_INITIALIZED = true;
    }
    logPageView();
  }, []);


  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: "#02001E",
        }}
      >
        <Providers>
          {/* {pathname !== "/" && <Header />} */}
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
