"use client";
import { Providers } from "../components/Providers";
import Header from "../components/Header";
import Script from "next/script";
import "../styles/main.scss";
// import { Metadata } from "next";
// import Favicon from "/public/images/favicon.png";

//TODO: Its use client so we can't use metadata in this part have to fix it
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by create next app",
//   icons: {
//     icon: Favicon.src,
//     apple: "",
//   },
// };

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" className='sr'>
      <body
        style={{
          backgroundColor: "#02001E",
        }}
      >
        <Script
          strategy="lazyOnload"
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}
        />

        <Script strategy="lazyOnload" id="">
          {`
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());
                    gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
                    page_path: window.location.pathname,
                    });
                `}
        </Script>
        <Providers>
          {/* {pathname !== "/" && <Header />} */}
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
